function eigv=qr_iter(A)
    A=hessenberg(A);
    last=diag(A,-1);
    n=size(A,1);
    err=0;
    tol=1e-6;%精度
    max_iter=1000;%最大迭代次数
    while(max_iter)
        sigma=A(end,end);
        [Q,R]=qr(A-sigma*eye(n));
        A=R*Q+sigma*eye(n);
        max_iter=max_iter-1;
        err=norm(diag(A,-1)-last);%次对角线的收敛性
        last=diag(A,-1);
        if(err<tol)
            break;
        end
    end
    if(max_iter==0)
        disp('达到最大迭代次数');
    end
    eigv=diag(R)+sigma;
end